---
name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: Add Mermaid
        env:
          MERMAID_HTML_TAG: |
            <script type='module'>
              import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
              mermaid.initialize({ startOnLoad: false });
              await mermaid.run({
                querySelector: 'pre > code.language-mermaid',
              });
            </script>
        run: |
          MERMAID_HTML_TAG="${MERMAID_HTML_TAG//\n'/}"
          grep -rl "language-mermaid" _site | while IFS= read -r file; do
            echo "Adding Mermaid to $file"
            sudo sed -i "s|</head>|$MERMAID_HTML_TAG\n</head>|" "$file"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
